# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4002dc5b06aab5b4d8378e81bf6d9adf2348fd1fd7335f4efdfbb871533e1d9f10a5ad77d9debda76ae44d89ca500012e486c3e9caf5eaad079638cf0217420f

test:
  secret_key_base: cdd00ec4a6e917fd7c1b2d6993e6c5d484b6a69a327cf0caa945e9bc992ed71381b3b7042c929476904ae0b07598543dfeb051160455616e382042cad85df57a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
